plugins:
  lti_enabled:
    default: false
  lti_authorization_endpoint:
    default: ""
  lti_client_id: 
    default: ""
  lti_platform_issuer_id:
    default: ""
  lti_platform_public_key:
    default: ""
    textarea: true
  lti_email_verified:
    default: false
